version: 1.0.{build}

image: Visual Studio 2017

platform:
  - x64

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 8 x64
  - yarn && cd app && yarn && yarn run rebuildwin && cd ..

build_script:
  - yarn run buildappveyor

test: off
