osx_image: xcode7.3

dist: trusty
sudo: required

language: c

env:
  - ELECTRON_CACHE=$HOME/.electron

matrix:
  include:
    - os: osx
    - os: linux
      env: CC=clang CXX=clang++ npm_config_clang=1
      compiler: clang

cache:
  directories:
    - $HOME/.electron

addons:
  apt:
    packages:
      - libgnome-keyring-dev
      - libsecret-1-dev
      - icnsutils
      - graphicsmagick
      - xz-utils
      - rpm
      - bsdtar

before_install:
  - mkdir -p /tmp/git-lfs && curl -L https://github.com/github/git-lfs/releases/download/v1.5.5/git-lfs-$([ "$TRAVIS_OS_NAME" == "linux" ] && echo "linux" || echo "darwin")-amd64-1.5.5.tar.gz | tar -xz -C /tmp/git-lfs --strip-components 1 && /tmp/git-lfs/git-lfs pull
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

install:
  - nvm install 7
  - yarn
  - yarn add electron-builder@next --dev # force install next version to test electron-builder
  - cd app && yarn && cd ..
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export LDFLAGS="-mmacosx-version-min=10.9" ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export CFLAGS="-mmacosx-version-min=10.9" ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export CXXFLAGS="-mmacosx-version-min=10.9" ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cd app/node_modules/sodium-native && npm install && npm run prebuild && rm -rf node_modules && cd ../../.. ; fi

script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then yarn run buildosx ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then yarn run buildlinux ; fi

branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
